#!/bin/bash
# script to run track Mhe for a list of N_mhe

for i in {2..17}
do
python track_exc_RT.py $i
done
#python track_excitations.py


#python track_excitations_mhe.py $'3' $'True' $'False' $'True'

#python track_excitations_mhe.py $'3' $'False' $'False' $'True'

